# Generated by Django 3.0.8 on 2020-07-19 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicosEProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servicos_produtos', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('faixa_de_preco', models.CharField(max_length=200)),
                ('validade_do_anuncio', models.CharField(max_length=200)),
                ('aceita_negociacoes', models.BooleanField(default=False)),
                ('telefone', models.IntegerField(max_length=14)),
                ('endereco', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=200)),
                ('cpf_ou_cnpj', models.IntegerField(max_length=15)),
                ('data', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
